### ISSUE TITLE
Failed to ingest data error

### ISSUE THREAD

**Issue by whackyhook** [mayooear/gpt4-pdf-chatbot-langchain#163]
Hi All, I get the below error when trying to run this - Any advice greatly appreciated

creating vector store...
error TypeError: this.pineconeIndex.upsert is not a function
    at PineconeStore.addVectors (C:\Users\John\Desktop\ps\gpt4-pdf-chatbot-langchain\node_modules\.pnpm\langchain@0.0.41_@pinecone-database+pinecone@0.0.10_pdf-parse@1.1.1\node_modules\langchain\src\vectorstores\pinecone.ts:65:32)
    at PineconeStore.addDocuments (C:\Users\John\Desktop\ps\gpt4-pdf-chatbot-langchain\node_modules\.pnpm\langchain@0.0.41_@pinecone-database+pinecone@0.0.10_pdf-parse@1.1.1\node_modules\langchain\src\vectorstores\pinecone.ts:39:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.fromDocuments (C:\Users\John\Desktop\ps\gpt4-pdf-chatbot-langchain\node_modules\.pnpm\langchain@0.0.41_@pinecone-database+pinecone@0.0.10_pdf-parse@1.1.1\node_modules\langchain\src\vectorstores\pinecone.ts:152:5)
    at run (c:\Users\John\Desktop\ps\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:37:5)
    at <anonymous> (c:\Users\John\Desktop\ps\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:49:3)
c:\Users\John\Desktop\ps\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:44
    throw new Error('Failed to ingest your data');
          ^

Error: Failed to ingest your data
    at run (c:\Users\John\Desktop\ps\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:44:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (c:\Users\John\Desktop\ps\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:49:3)

**Comment by whackyhook** [comment]
Worked, thank you!
