### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by rossman22590** [mayooear/gpt4-pdf-chatbot-langchain#21]
This is on localhost and I get same error on Vercel:

      type: 'apiMessage'
    }
  ],
  history: [],
  pendingSourceDocs: []
}
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <div>. See https://reactjs.org/link/warning-keys for more information.
    at Home (webpack-internal:///./pages/index.tsx:32:78)
    at main
    at MyApp (webpack-internal:///./pages/_app.tsx:14:18)
    at StyleRegistry (C:\Users\Ross\Desktop\Github Projects\gpt4-pdf-chatbot-langchain-1\node_modules\styled-jsx\dist\index\index.js:449:36)
    at PathnameContextProviderAdapter (C:\Users\Ross\Desktop\Github Projects\gpt4-pdf-chatbot-langchain-1\node_modules\next\dist\shared\lib\router\adapters.js:60:11)
    at AppContainer (C:\Users\Ross\Desktop\Github Projects\gpt4-pdf-chatbot-langchain-1\node_modules\next\dist\server\render.js:291:29)
    at AppContainerWithIsomorphicFiberStructure (C:\Users\Ross\Desktop\Github Projects\gpt4-pdf-chatbot-langchain-1\node_modules\next\dist\server\render.js:327:57)
    at div
    at Body (C:\Users\Ross\Desktop\Github Projects\gpt4-pdf-chatbot-langchain-1\node_modules\next\dist\server\render.js:614:21)
wait  - compiling /api/chat (client and server)...
event - compiled successfully in 93 ms (75 modules)

**Comment by mayooear** [comment]
I merged a PR yesterday to handle this. Have you updated the changes?

**Comment by jokerlee** [comment]
> 
same issue here, use the latest code.

`messageState {
  messages: [
    {
      message: 'Hi, what would you like to learn about this legal case?',
      type: 'apiMessage'
    }
  ],
  history: [],
  pendingSourceDocs: []
}
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <div>. See https://reactjs.org/link/warning-keys for more information.
    at Home (webpack-internal:///./pages/index.tsx:32:78)
    at main
    at MyApp (webpack-internal:///./pages/_app.tsx:14:18)
    at StyleRegistry (/home/joker/gpt/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/styled-jsx@5.1.1_react@18.2.0/node_modules/styled-jsx/dist/index/index.js:449:36)
    at PathnameContextProviderAdapter (/home/joker/gpt/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/shared/lib/router/adapters.js:60:11)
    at AppContainer (/home/joker/gpt/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/render.js:291:29)
    at AppContainerWithIsomorphicFiberStructure (/home/joker/gpt/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/render.js:327:57)
    at div
    at Body (/home/joker/gpt/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/render.js:614:21)
messageState {
  messages: [
    {
      message: 'Hi, what would you like to learn about this legal case?',
      type: 'apiMessage'
    }
  ],
  history: [],
  pendingSourceDocs: []
}`

**Comment by mayooear** [comment]
> same issue here, use the latest code, centos7 self-hosted
> 
> `messageState { messages: [ { message: 'Hi, what would you like to learn about this legal case?', type: 'apiMessage' } ], history: [], pendingSourceDocs: [] } Warning: Each child in a list should have a unique "key" prop.
> 
> Check the top-level render call using
> 
> . See https://reactjs.org/link/warning-keys for more information.
> at Home (webpack-internal:///./pages/index.tsx:32:78)
> at main
> at MyApp (webpack-internal:///./pages/_app.tsx:14:18)
> at StyleRegistry (/home/joker/gpt/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/styled-jsx@5.1.1_react@18.2.0/node_modules/styled-jsx/dist/index/index.js:449:36)
> at PathnameContextProviderAdapter (/home/joker/gpt/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/[next@13.2.3_biqbaboplfbrettd7655fr4n2y](mailto:next@13.2.3_biqbaboplfbrettd7655fr4n2y)/node_modules/next/dist/shared/lib/router/adapters.js:60:11)
> at AppContainer (/home/joker/gpt/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/[next@13.2.3_biqbaboplfbrettd7655fr4n2y](mailto:next@13.2.3_biqbaboplfbrettd7655fr4n2y)/node_modules/next/dist/server/render.js:291:29)
> at AppContainerWithIsomorphicFiberStructure (/home/joker/gpt/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/[next@13.2.3_biqbaboplfbrettd7655fr4n2y](mailto:next@13.2.3_biqbaboplfbrettd7655fr4n2y)/node_modules/next/dist/server/render.js:327:57)
> at div
> at Body (/home/joker/gpt/gpt4-pdf-chatbot-langchain/node_modules/.pnpm/[next@13.2.3_biqbaboplfbrettd7655fr4n2y](mailto:next@13.2.3_biqbaboplfbrettd7655fr4n2y)/node_modules/next/dist/server/render.js:614:21)
> messageState {
> messages: [
> {
> message: 'Hi, what would you like to learn about this legal case?',
> type: 'apiMessage'
> }
> ],
> history: [],
> pendingSourceDocs: []
> }`

Does the warning prevent the code from running?

**Comment by rossman22590** [comment]
I fixed the  project by using docker
