### ISSUE TITLE
error on - npm injest

### ISSUE THREAD

**Issue by wargsm** [mayooear/gpt4-pdf-chatbot-langchain#243]
Pinecone/OpenAI credentials are valid, confirmed from other projects. My /docs/sample.txt file just contains "my name is Firstname Surname".  Clean project...  Error below on npm inject. Any thoughts? Please and thanks.

`macpro@macpro gpt4-pdf-chatbot-langchain % npm run ingest

> gpt4-langchain-pdf-chatbot@0.1.0 ingest
> tsx -r dotenv/config scripts/ingest-data.ts

/Users/macpro/projects/gpt4-pdf-chatbot-langchain/node_modules/tsx/dist/cli.js:2
import ys from"tty";import{v as ws}from"./package-69a34105.js";import{r as Dt}from"./pkgroll_create-require-b9328ee2.js";import{pathToFileURL as Rs,fileURLToPath as bs}from"url";import vs from"child_process";import K from"path";import ie from"fs";import Fu,{constants as Bs}from"os";import Ss from"events";import me from"util";import $s from"stream";import"module";const Ts="known-flag",xs="unknown-flag",Os="argument",{stringify:_e}=JSON,Ns=/\B([A-Z])/g,Hs=t=>t.replace(Ns,"-$1").toLowerCase(),{hasOwnProperty:Ps}=Object.prototype,Ae=(t,e)=>Ps.call(t,e),Ls=t=>Array.isArray(t),gu=t=>typeof t=="function"?[t,!1]:Ls(t)?[t[0],!0]:gu(t.type),Is=(t,e)=>t===Boolean?e!=="false":e,ks=(t,e)=>typeof e=="boolean"?e:t===Number&&e===""?Number.NaN:t(e),Ms=/[\s.:=]/,Ws=t=>{const e=`Flag name ${_e(t)}`;if(t.length===0)throw new Error(`${e} cannot be empty`);if(t.length===1)throw new Error(`${e} must be longer than a character`);const u=t.match(Ms);if

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)`

**Comment by fabianhug** [comment]
save it as a `*.PDF` and try again @wargsm

**Comment by spacepirate0001** [comment]
Support for .txt files is coming in PR #246
