### ISSUE TITLE
Issue with 'ERR_NETWORK'

### ISSUE THREAD

**Issue by KowComical** [mayooear/gpt4-pdf-chatbot-langchain#276]
Hi guys, I followed everything in the instruction and encounter below error:
```
url: 'https://api.openai.com/v1/embeddings'
  },
  code: 'ERR_NETWORK',
  request: Request {
    [Symbol(realm)]: { settingsObject: [Object] },
    [Symbol(state)]: {
      method: 'POST',
      localURLsOnly: false,
      unsafeRequest: false,
      body: [Object],
      client: [Object],
      reservedClient: null,
      replacesClientId: '',
      window: 'client',
      keepalive: false,
      serviceWorkers: 'all',
      initiator: '',
      destination: '',
      priority: null,
      origin: 'client',
      policyContainer: 'client',
      referrer: 'client',
      referrerPolicy: '',
      mode: 'cors',
      useCORSPreflightFlag: false,
      credentials: 'same-origin',
      useCredentials: false,
      cache: 'default',
      redirect: 'follow',
      integrity: '',
      cryptoGraphicsNonceMetadata: '',
      parserMetadata: '',
      reloadNavigation: false,
      historyNavigation: false,
      userActivation: false,
      taintedOrigin: false,
      redirectCount: 0,
      responseTainting: 'basic',
      preventNoCacheCacheControlHeaderModification: false,
      done: false,
      timingAllowFailed: false,
      headersList: [HeadersList],
      urlList: [Array],
      url: [URL]
    },
    [Symbol(signal)]: AbortSignal { aborted: false },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON],
  attemptNumber: 7,
  retriesLeft: 0
}
k:\Github\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:44
    throw new Error('Failed to ingest your data');
          ^


Error: Failed to ingest your data
    at run (k:\Github\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:44:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (k:\Github\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:49:3)
 ```   
can anyone tell me how to fix this? :( i been trying to find a solution for a day now:(

**Comment by sibylare** [comment]
same error

**Comment by RichardTaoK** [comment]
+1

**Comment by sgch1982** [comment]
+1

**Comment by LemonSuger** [comment]
+1

**Comment by LemonSuger** [comment]
change other vpn server

**Comment by BigJe8** [comment]
same error
