### ISSUE TITLE
Check the top-level render call using <div>

### ISSUE THREAD

**Issue by sibylare** [mayooear/gpt4-pdf-chatbot-langchain#289]
gpt4-langchain-pdf-chatbot@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /content/.env
event - compiled client and server successfully in 1594 ms (173 modules)
wait  - compiling...
event - compiled successfully in 228 ms (139 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 2.1s (1321 modules)
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <div>. See https://reactjs.org/link/warning-keys for more information.
    at Home (webpack-internal:///./pages/index.tsx:29:78)
    at main
    at MyApp (webpack-internal:///./pages/_app.tsx:14:18)
    at StyleRegistry (/content/node_modules/styled-jsx/dist/index/index.js:449:36)
    at PathnameContextProviderAdapter (/content/node_modules/next/dist/shared/lib/router/adapters.js:60:11)
    at AppContainer (/content/node_modules/next/dist/server/render.js:291:29)
    at AppContainerWithIsomorphicFiberStructure (/content/node_modules/next/dist/server/render.js:327:57)
    at div
    at Body (/content/node_modules/next/dist/server/render.js:614:21)

At the same time, when i send message, An error occurred while fetching the data. Please try again.

I found that the author has previously addressed this issue and I am using the latest version of the code. I don't know why the problem still occurs.

**Comment by dissorial** [comment]
That 'Warning: Each child in a list should have a unique "key" prop.' does not prevent one from using the app. The real issue here is with the fact that you got an error while fetching the data. Can you share more details on that?

**Comment by sibylare** [comment]
> 

![49600cb33320fc05b41d795b7bc3553](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/27347674/8e6076b3-03af-458f-ac72-a445d645d1b0)

**Comment by dissorial** [comment]
If the server responded iwth status code 500, it means that either your pinecone or openai api configuration is not set up correctly.
