### ISSUE TITLE
Is Chinese supported?

### ISSUE THREAD

**Issue by Conor-heming** [mayooear/gpt4-pdf-chatbot-langchain#329]
pdf文件内容是中文内容导致的问题吗？
我的报错：Syntax error "t"

**Comment by Conor-heming** [comment]
详细报错： ERROR: Syntax error "t"
    at failureErrorWithLog (D:\code\gpt\gpt4-pdf-chatbot-langchain-main\node_modules\esbuild\lib\main.js:1636:15)
    at D:\code\gpt\gpt4-pdf-chatbot-langchain-main\node_modules\esbuild\lib\main.js:837:29
    at responseCallbacks.<computed> (D:\code\gpt\gpt4-pdf-chatbot-langchain-main\node_modules\esbuild\lib\main.js:697:9)
    at handleIncomingPacket (D:\code\gpt\gpt4-pdf-chatbot-langchain-main\node_modules\esbuild\lib\main.js:752:9)
    at Socket.readFromStdout (D:\code\gpt\gpt4-pdf-chatbot-langchain-main\node_modules\esbuild\lib\main.js:673:7)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 59,
        file: 'D:\\code\\gpt\\gpt4-pdf-chatbot-langchain-main\\scripts\\ingest-data.ts',
        length: 0,
        line: 1,
        lineText: "/import { RecursiveCharacterTextSplitter } from 'langchain/text_splitter';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Syntax error "t"'
    }
  ],
  warnings: []
}

**Comment by choogoo** [comment]
中文pdf是支持的，但是如何让回答的内容是中文呢

**Comment by j796160836** [comment]
I found this pull request done the good job.
https://github.com/mayooear/gpt4-pdf-chatbot-langchain/pull/340/files#
