### ISSUE TITLE
npm run ingest return 429 error

### ISSUE THREAD

**Issue by barbie6676** [mayooear/gpt4-pdf-chatbot-langchain#342]
```
~/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:46
    throw new Error('Failed to ingest your data');
          ^


Error: Failed to ingest your data
    at run (~/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:46:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (~/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:51:3)

Node.js v18.16.0
```
```
creating vector store...
error Error: Request failed with status code 429
    at createError (~/gpt4-pdf-chatbot-langchain/node_modules/axios/lib/core/createError.js:16:15)
    at settle (~/gpt4-pdf-chatbot-langchain/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (~/gpt4-pdf-chatbot-langchain/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
```

**Comment by barbie6676** [comment]
it was a small pdf with only 3 pages and mainly text.

**Comment by linkstatic12** [comment]
did u create a index in pinecone?

**Comment by barbie6676** [comment]
yes I did created index in pinecone. 
<img width="979" alt="Screenshot 2023-06-07 at 3 42 44 PM" src="https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/1864568/4b9c9966-3633-46a4-891b-a06889178bdc">

**Comment by lkh9908** [comment]
did you solve it?

**Comment by lkh9908** [comment]
dimension needs to be 1536 i think, but i still have the same error

**Comment by AvishalomJ** [comment]
It could be related to your credits in OpenAI.
Check that your credits didn't expire here - https://platform.openai.com/account/usage

**Comment by tanld7** [comment]
I also have a small pdf and face the same error. I still have enough OpenAI credit.

**Comment by linkstatic12** [comment]
is it possible to share this pdf. Sometimes the pdf isn't converted.

**Comment by barbie6676** [comment]
hi I resolved the issue, it turned out to be not enough openAPI balance
