### ISSUE TITLE
failed to ingest: 400 bad request the plain http request was sent to HTTPS port

### ISSUE THREAD

**Issue by holyvslin** [mayooear/gpt4-pdf-chatbot-langchain#372]
As network connection must be configured proxy like **http**://IP:**8080**, so always response error: **400 bad request the plain http request was sent to HTTPS port** when execute command "npm run ingest". 

**output:**
```
creating vector store...
error Error: Request failed with status code 400
    at createError (~/gpt4-pdf-chatbot-langchain/node_modules/axios/lib/core/createError.js:16:15)
    at settle (~/gpt4-pdf-chatbot-langchain/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (~/gpt4-pdf-chatbot-langchain/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
**Wireshark log:**
![image](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/assets/43088535/c9e2dbd3-e2f5-444d-a2b8-9926dba81e1c)

But open [link ](https://api.openai.com/v1/embeddings) on explorer(chrome/firefox) with same proxy **http**://IP:**8080** is OK.

Ask support how to keep same proxy to fix or skip this Error?
Thanks

**Comment by holyvslin** [comment]
refer to 
https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/336#issuecomment-1596703299 

Fixed by Replace
`const embeddings = new OpenAIEmbeddings();`
to
`   const agent = new HttpsProxyAgent('http://IP:8080')
    const embeddings = new OpenAIEmbeddings({
          verbose: true,
          openAIApiKey: 'XXX'
          },
          {
          baseOptions: {
              proxy: false,
              httpAgent: agent,
              httpsAgent: agent,
          },
      });`

**Comment by holyvslin** [comment]
Fixed as above comments
