### ISSUE TITLE
ReferenceError: ReadableStream is not defined

### ISSUE THREAD

**Issue by hhoanganh** [mayooear/gpt4-pdf-chatbot-langchain#396]
I got this error while i run 'npm run ingest'

> gpt4-langchain-pdf-chatbot@0.1.0 ingest C:\Users\HP\Documents\GitHub\gpt4-pdf-chatbot-langchain
> tsx -r dotenv/config scripts/ingest-data.ts

ReferenceError: ReadableStream is not defined
    at file:///C:/Users/HP/Documents/GitHub/gpt4-pdf-chatbot-langchain/node_modules/langchain/dist/util/stream.js:41:45
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gpt4-langchain-pdf-chatbot@0.1.0 ingest: `tsx -r dotenv/config scripts/ingest-data.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gpt4-langchain-pdf-chatbot@0.1.0 ingest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2023-08-21T05_19_58_504Z-debug.log

**Comment by hhoanganh** [comment]
I fixed by installing yarn at root folder.
