### ISSUE TITLE
Error when trying to transition from GPT-4 to PaLM

### ISSUE THREAD

**Issue by F4brizio** [mayooear/gpt4-pdf-chatbot-langchain#423]
I'm trying to implement PaLM as a replacement for ChatGPT, but so far, I haven't had any luck.

My code:

chat-bot.ts
```js
import type { NextApiRequest, NextApiResponse } from 'next';
import { OpenAIEmbeddings } from 'langchain/embeddings/openai';
import { GooglePaLMEmbeddings } from 'langchain/embeddings/googlepalm';
import { PineconeStore } from 'langchain/vectorstores/pinecone';
import { AIMessage, HumanMessage } from 'langchain/schema';
import { makeChain } from '@/utils/makechain-palm';
import { pinecone } from '@/utils/pinecone-client-palm';
import { PINECONE_INDEX_NAME, PINECONE_NAME_SPACE } from '@/config/pinecone-palm';
```
...
```js
  const sanitizedQuestion = question.trim().replaceAll('\n', ' ');
      const index = pinecone.Index(PINECONE_INDEX_NAME);
      const vectorStore = await PineconeStore.fromExistingIndex(
          new GooglePaLMEmbeddings({
              apiKey: process.env.GOOGLE_PALM_API_KEY,
          }),
          {
              pineconeIndex: index,
              textKey: 'text',
              namespace: PINECONE_NAME_SPACE, //namespace comes from your config folder
          },
      );
      const pastMessages = history.map((message: string, i: number) => {
          if (i % 2 === 0) {
              console.log('HumanMessage', message, 'i', i);
              return new HumanMessage(message); // Assuming HumanMessage is the correct type
          } else {
              console.log('AIMessage', message, 'i', i);
              return new AIMessage(message); // Assuming AIMessage is the correct type
          }
      });
      const chain = makeChain(vectorStore);
      try {
          const response = await chain.call({
              question: sanitizedQuestion,
              chat_history: pastMessages || [],
          });
          console.log('response', response);
          res.status(200).json(response);
      
      } catch (error: any) {
          console.log('error', error);
          res.status(500).json({error: error.message || "Something went wrong"});
      }
  }
```

makechain-palm.ts
```js
import {ChatGooglePaLM} from "langchain/chat_models/googlepalm";
import {PineconeStore} from 'langchain/vectorstores/pinecone';
import {ConversationalRetrievalQAChain} from 'langchain/chains';

let CONDENSE_TEMPLATE = ...
let QA_TEMPLATE = ...

export const makeChain = (vectorstore: PineconeStore) => {
    console.log('process.env.GOOGLE_PALM_API_KEY', process.env.GOOGLE_PALM_API_KEY);
    const modelPaLM = new ChatGooglePaLM({
        apiKey: process.env.GOOGLE_PALM_API_KEY,
        temperature: 0,
        modelName: "models/chat-bison-001"
    });
    return ConversationalRetrievalQAChain.fromLLM(
      modelPaLM,
      vectorstore.asRetriever(),
      {
          qaTemplate: QA_TEMPLATE,
          questionGeneratorTemplate: CONDENSE_TEMPLATE,
          returnSourceDocuments: true,
      },
  );
};
```

pinecone-client-palm.ts
```js
import {Pinecone} from "@pinecone-database/pinecone";

if (!process.env.PINECONE_PALM_ENVIRONMENT || !process.env.PINECONE_PALM_API_KEY) {
  throw new Error('Pinecone environment or api key vars missing');
}

async function initPinecone() {
  try {
    return new Pinecone({
      environment: process.env.PINECONE_PALM_ENVIRONMENT ?? '',
      apiKey: process.env.PINECONE_PALM_API_KEY ?? '',
    });
  } catch (error) {
    console.log('error', error);
    throw new Error('Failed to initialize Pinecone Client');
  }
}

export const pinecone = await initPinecone();
```

package.json
```json
  "dependencies": {
    "@google-ai/generativelanguage": "^0.2.1",
    "@radix-ui/react-accordion": "^1.1.1",
    "@pinecone-database/pinecone": "^0.0.14",
    "clsx": "^1.2.1",
    "dotenv": "^16.3.1",
    "google-auth-library": "^8.9.0",
    "pdf-parse": "^1.1.1",
    "next": "13.5.6",
    "react": "^18",
    "react-markdown": "^8.0.5",
    "lucide-react": "^0.125.0",
    "react-dom": "^18",
    "tailwind-merge": "^1.10.0",
    "langchain": "^0.0.151"
  },
```

I have the following error:
```
error TypeError: Cannot read properties of undefined (reading 'text')
    at NoOpOutputParser.parseResult (file:///C:/Users/ASUS/Desktop/tmp-dev/chatbot/node_modules/langchain/dist/schema/output_parser.js:43:42)
    at NoOpOutputParser.parseResultWithPrompt (file:///C:/Users/ASUS/Desktop/tmp-dev/chatbot/node_modules/langchain/dist/schema/output_parser.js:17:21)
    at LLMChain._getFinalOutput (file:///C:/Users/ASUS/Desktop/tmp-dev/chatbot/node_modules/langchain/dist/chains/llm_chain.js:93:55)
    at LLMChain._call (file:///C:/Users/ASUS/Desktop/tmp-dev/chatbot/node_modules/langchain/dist/chains/llm_chain.js:123:42)
    at async LLMChain.call (file:///C:/Users/ASUS/Desktop/tmp-dev/chatbot/node_modules/langchain/dist/chains/base.js:101:28)
    at async StuffDocumentsChain._call (file:///C:/Users/ASUS/Desktop/tmp-dev/chatbot/node_modules/langchain/dist/chains/combine_docs_chain.js:59:24)
    at async StuffDocumentsChain.call (file:///C:/Users/ASUS/Desktop/tmp-dev/chatbot/node_modules/langchain/dist/chains/base.js:101:28)
    at async ConversationalRetrievalQAChain._call (file:///C:/Users/ASUS/Desktop/tmp-dev/chatbot/node_modules/langchain/dist/chains/conversational_retrieval_chain.js:143:24)
    at async ConversationalRetrievalQAChain.call (file:///C:/Users/ASUS/Desktop/tmp-dev/chatbot/node_modules/langchain/dist/chains/base.js:101:28)
    at async handler (webpack-internal:///(api)/./pages/api/chat-bot.ts:51:26)
```

Any suggestions?

**Comment by mpakaris** [comment]
the newest pinecone does not require environment variable
