### ISSUE TITLE
Fail to ingest data

### ISSUE THREAD

**Issue by fraction94** [mayooear/gpt4-pdf-chatbot-langchain#468]
I have followed the readme instructions and created an index in Pinecone. However, still fail to ingest data and keep on getting this error. I dont know what am I doing wrong. I am fairly new to this and trying to learn along the way. any help is much appreciated. 

`creating vector store...
error TypeError: Cannot read properties of undefined (reading 'text')
    at C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\utils.js:44:57   
    at step (C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\utils.js:33:23)
    at Object.next (C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\utils.js:14:53)
    at C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\utils.js:8:71    
    at new Promise (<anonymous>)
    at __awaiter (C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\utils.js:4:12)
    at extractMessage (C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\utils.js:40:48)
    at C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\handling.js:66:70
    at step (C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\handling.js:33:23)
    at Object.next (C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\handling.js:14:53)

file:///C:/Python/gpt4-pdf/scripts/ingest-data.ts:46
    throw new Error('Failed to ingest your data');
          ^
Error: Failed to ingest your data
    at run (file:///C:/Python/gpt4-pdf/scripts/ingest-data.ts:46:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///C:/Python/gpt4-pdf/scripts/ingest-data.ts:51:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by fraction94** [comment]
Apologies for being so dumb, but which part of the program should I use this code in?

**Comment by fraction94** [comment]
i have tried it but still not working. I get the following error. my pdf is simplest document of few pages which I converted from word to PDF so it is text property. looks like OpenAI works fine but Pinecone is not. any help is greatly appreciated. 

 Document {
    pageContent: '8  \n' +
      '  \n' +
      'diverse cultures, Rocky Mountains, Niagara Falls, hospitality and Canadian cities. The greatest  \n' +
      'Canadians that you should know include; Wayne Gretzky. Tommy Douglas, Dr. Roberta Bondar,  \n' +
      'Pierre Trudeau, and Terrance Stanley Fox. The five common Canadian musicians include  \n' +
      'Leonard Cohen, Celine Dion, The Tragically Hip (Gord Downie as lead singer), Joni Mitchell  \n' +
      'and Shania Twain. Canada has had great inventions which have been impacts to the world the  \n' +
      'inventors are Alexander Graham Bell (telephone), Mathew Evans and Henry Woodward (first  \n' +
      'electric bulb), Sir Sandford Fleming (standard time), James Naismith (basketball), and Arthur  \n' +
      'Sicard (snowblower).',
    metadata: {
      source: 'C:\\Python\\gpt4-pdf\\docs\\testcase.pdf',
      pdf: [Object],
      loc: [Object]
    }
  }
]
creating vector store...
error TypeError: Cannot read properties of undefined (reading 'text')
    at C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\utils.js:44:57
    at step (C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\utils.js:33:23)
    at Object.next (C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\utils.js:14:53)
    at C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\utils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\utils.js:4:12)
    at extractMessage (C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\utils.js:40:48)        
    at C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\handling.js:66:70
    at step (C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\handling.js:33:23)
    at Object.next (C:\Python\gpt4-pdf\node_modules\@pinecone-database\pinecone\dist\errors\handling.js:14:53)        

file:///C:/Python/gpt4-pdf/scripts/ingest-data.ts:39
    throw new Error('Failed to ingest your data');
          ^
Error: Failed to ingest your data
    at run (file:///C:/Python/gpt4-pdf/scripts/ingest-data.ts:39:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///C:/Python/gpt4-pdf/scripts/ingest-data.ts:44:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


Also this is how i setup my .env file

`OPENAI_API_KEY=sk-proj-zxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Update these with your pinecone details from your dashboard.
# PINECONE_INDEX_NAME is in the indexes tab under "index name" in blue
# PINECONE_ENVIRONMENT is in indexes tab under "Environment". Example: "us-east1-gcp"
PINECONE_API_KEY=4d8dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
PINECONE_ENVIRONMENT=us-east-1
`PINECONE_INDEX_NAME=pdf`
