### ISSUE TITLE
ingest fails with `Cannot read properties of undefined (reading 'text')`

### ISSUE THREAD

**Issue by dmotxilla** [mayooear/gpt4-pdf-chatbot-langchain#472]
The README says:
```
Visit [pinecone](https://pinecone.io/) to create and retrieve your API keys, and also retrieve your environment and index name from the dashboard.
```
but I do not see an "environment" variable.
I create a pinecone account, I get the api key (and I use it for OPENAI_API_KEY), I create an index with name "index1" (and I use it for PINECONE_INDEX_NAME), with default parameters. I see a "Region" parameter with value "us-east-1". Is that what I need to use for `PINECONE_ENVIRONMENT` ?

![image](https://github.com/user-attachments/assets/9d74cfbd-f4b0-42a5-9f45-7dd9cbcb1746)

but then, the ingest fails with `Cannot read properties of undefined (reading 'text')`.

```
$ yarn run ingest

creating vector store...
error TypeError: Cannot read properties of undefined (reading 'text')
    at /home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/utils.js:44:57
    at step (/home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/utils.js:33:23)
    at Object.next (/home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/utils.js:14:53)
    at /home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/utils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/utils.js:4:12)
    at extractMessage (/home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/utils.js:40:48)
    at /home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:66:70
    at step (/home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:33:23)
    at Object.next (/home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:14:53)

file:///home/david/test1/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:46
    throw new Error('Failed to ingest your data');
          ^
Error: Failed to ingest your data
    at run (file:///home/david/test1/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:46:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///home/david/test1/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:51:3
```

**Comment by dmotxilla** [comment]
thanks for the answer.
The "Region" parameter "us-east-1" was indeed not correct.
I now tried with the value "us-east1-gcp", and it works better, but it still fails.
(by the way, in the pinecone website, I don't see this "us-east1-gcp" value anywhere, nor a "Environment" parameter. Maybe because I have the free account with the Default project? Where do I see the name of the environment, can you please make a screenshot?)

Anyway, using the value "us-east1-gcp" as PINECONE_ENVIRONMENT works a bit better, but it still fails:

the documents returned by textSplitter.splitDocuments(rawDocs) do not have a 'text' property. They have a `pageContent` instead. Is this ok? Anyway, it does not complain about the `text` property anymore. It complains about "Verify you have the correct environment, project id, and index name configured.". 
The index name is correct, I guess, as shown in the screenshot in the previous message. The API key is also correct, I think. The environment, I am not sure. If I use "us-east-1" or something like "hahha", I get the `text` error. However, using the "us-east1-gcp" value, if fails with something different. Again, I checked all the web console of my pinecone account (free account), and I don't see a Environment parameter anywhere.


```
$ cat .env
OPENAI_API_KEY=sk-proj-QPLoQyqRqnNtzklWHrqFT3BlbkFJKm...
PINECONE_API_KEY=ae9ac4c6-fa87-49c2-bde0-21....
PINECONE_ENVIRONMENT=us-east1-gcp
PINECONE_INDEX_NAME=index1

$ yarn run ingest
yarn run v1.22.22
$ tsx -r dotenv/config scripts/ingest-data.ts
(node:2096485) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
rawDocs [
  Document {
    pageContent: '  \n' +
      '                                          Non-chemical                                          crop                                          protection                                           \n' +
      '6   \n' +
      '1     Introduction \n' +
      '1.1    What is this booklet about?  \n' +
      'As  a  farmer  of  arable  crops  or  vegetables,  you  strive  to  achieve  the   \n' +
      'highest  yield  and  the  best  quality  product  possible.  Of  course  you   \n' +
      'would prefer to do this with a minimum investment of energy and re- \n' +
      'sources,  but  you  are  continuously  bothered  by  all  kinds  of  harmful   \n' +
      'organisms (pests) that threaten to  reduce the quality and yield of your  \n' +
      'crops.  Protecting  your  crops  from  these  pests  is  extremely  important,   \n' +
      'but  it  is  difficult  to  achieve  maximum  results  with  a  minimum  of  ef- \n' +
      'fort.  You  have  to  look  not  only  at  a  measure’s  immediate  effect,  but   \n' +
      'also at its long-term effect.   \n' +
      'This  booklet  gives  an  overview  of  the  main  non-chemical  measures   \n' +
      'you can take to protect your crops from pests. Most of these measures  \n' +
      'are  preventive:  they  involve  planning  and  farming  practices  that  will   \n' +
      'help you to keep pest numbers down and limit the damage they do.  \n' +
      '1.2    Why publish a booklet about non-chemical  \n' +
      'crop protection?  \n' +
      'Non-chemical methods of crop protection have always been practised,  \n' +
      'but the introduction of chemical pesticides a few decades ago seemed  \n' +
      'to  make  crop  protection  a  lot  easier.  As  a  farmer,  you  suddenly  only   \n' +
      'needed  to  know  which  particular  pests  you  were  dealing  with,  which   \n' +
      'pesticides  were  available  to  control  them,  and  how  to  apply  these   \n' +
      'products safely. These products were so effective that it looked at first  \n' +
      'as  though  all  pests  could  be  eradicated  in  this  way.  In  practice,  how- \n' +
      'ever,  the  pests  were  not  actually  eradicated,  because  they  came  back   \n' +
      'every growing season. Many natural enemies were temporarily wiped  \n' +
      'out along with the pests, which gave the pests the opportunity to mul- \n' +
      'tiply even more explosively than before (see case 1 for an example).  \n' +
      'To ensure a healthy crop, it was often necessary to spray several times  \n' +
      'per season just to control one type of pest. Eventually, some pesticides ',
    metadata: {
      source: '/home/david/test1/gpt4-pdf-chatbot-langchain/docs/sample.pdf',
      pdf: [Object],
      loc: [Object]
    }
  }
]
split docs [
  Document {
    pageContent: 'Non-chemical                                          crop                                          protection                                           \n' +
      '6   \n' +
      '1     Introduction \n' +
      '1.1    What is this booklet about?  \n' +
      'As  a  farmer  of  arable  crops  or  vegetables,  you  strive  to  achieve  the   \n' +
      'highest  yield  and  the  best  quality  product  possible.  Of  course  you   \n' +
      'would prefer to do this with a minimum investment of energy and re- \n' +
      'sources,  but  you  are  continuously  bothered  by  all  kinds  of  harmful   \n' +
      'organisms (pests) that threaten to  reduce the quality and yield of your  \n' +
      'crops.  Protecting  your  crops  from  these  pests  is  extremely  important,   \n' +
      'but  it  is  difficult  to  achieve  maximum  results  with  a  minimum  of  ef- \n' +
      'fort.  You  have  to  look  not  only  at  a  measure’s  immediate  effect,  but   \n' +
      'also at its long-term effect.',
    metadata: {
      source: '/home/david/test1/gpt4-pdf-chatbot-langchain/docs/sample.pdf',
      pdf: [Object],
      loc: [Object]
    }
  },
  Document {
    pageContent: 'but  it  is  difficult  to  achieve  maximum  results  with  a  minimum  of  ef- \n' +
      'fort.  You  have  to  look  not  only  at  a  measure’s  immediate  effect,  but   \n' +
      'also at its long-term effect.   \n' +
      'This  booklet  gives  an  overview  of  the  main  non-chemical  measures   \n' +
      'you can take to protect your crops from pests. Most of these measures  \n' +
      'are  preventive:  they  involve  planning  and  farming  practices  that  will   \n' +
      'help you to keep pest numbers down and limit the damage they do.  \n' +
      '1.2    Why publish a booklet about non-chemical  \n' +
      'crop protection?  \n' +
      'Non-chemical methods of crop protection have always been practised,  \n' +
      'but the introduction of chemical pesticides a few decades ago seemed  \n' +
      'to  make  crop  protection  a  lot  easier.  As  a  farmer,  you  suddenly  only   \n' +
      'needed  to  know  which  particular  pests  you  were  dealing  with,  which   \n' +
      'pesticides  were  available  to  control  them,  and  how  to  apply  these',
    metadata: {
      source: '/home/david/test1/gpt4-pdf-chatbot-langchain/docs/sample.pdf',
      pdf: [Object],
      loc: [Object]
    }
  },
  Document {
    pageContent: 'needed  to  know  which  particular  pests  you  were  dealing  with,  which   \n' +
      'pesticides  were  available  to  control  them,  and  how  to  apply  these   \n' +
      'products safely. These products were so effective that it looked at first  \n' +
      'as  though  all  pests  could  be  eradicated  in  this  way.  In  practice,  how- \n' +
      'ever,  the  pests  were  not  actually  eradicated,  because  they  came  back   \n' +
      'every growing season. Many natural enemies were temporarily wiped  \n' +
      'out along with the pests, which gave the pests the opportunity to mul- \n' +
      'tiply even more explosively than before (see case 1 for an example).  \n' +
      'To ensure a healthy crop, it was often necessary to spray several times  \n' +
      'per season just to control one type of pest. Eventually, some pesticides',
    metadata: {
      source: '/home/david/test1/gpt4-pdf-chatbot-langchain/docs/sample.pdf',
      pdf: [Object],
      loc: [Object]
    }
  }
]
creating vector store...
error PineconeConnectionError: Request failed to reach Pinecone. Verify you have the correct environment, project id, and index name configured.
    at /home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:52:39
    at step (/home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:33:23)
    at Object.next (/home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:14:53)
    at /home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:4:12)
    at handleFetchError (/home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:47:67)
    at /home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:62:54
    at step (/home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:33:23)
    at Object.next (/home/david/test1/gpt4-pdf-chatbot-langchain/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:14:53) {
  attemptNumber: 7,
  retriesLeft: 0
}

file:///home/david/test1/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:47
    throw new Error('Failed to ingest your data');
          ^
Error: Failed to ingest your data
    at run (file:///home/david/test1/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:47:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///home/david/test1/gpt4-pdf-chatbot-langchain/scripts/ingest-data.ts:52:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dmotxilla** [comment]
I asked Pinecone about it:
https://community.pinecone.io/t/how-to-find-out-what-is-my-environment-name-in-a-free-pinecone-account/6253

Reply:
It looks like that code is using the older connection method which is not supported with Serverless indexes.

[gpt4-pdf-chatbot-langchain](https://github.com/mayooear/gpt4-pdf-chatbot-langchain) needs to be updated to use the latest version of the NodeJS SDK.

**Comment by dmotxilla** [comment]
I close this issue, as the original subject was solved, and I created a new ticket with the current issue.
https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/473
